INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('anna@gmail.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('anna@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test1@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test2@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test3@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test4@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test5@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test6@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('admin@springweb.com','12345',TRUE); 

INSERT INTO AUTHORITIES (USERNAME,AUTHORITY) VALUES ('anna@gmail.com','ROLE_ADMIN');
INSERT INTO AUTHORITIES (USERNAME,AUTHORITY) VALUES ('anna@outlook.com','ROLE_ADMIN');
INSERT INTO AUTHORITIES (USERNAME,AUTHORITY) VALUES ('test@outlook.com','ROLE_USER');

INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 1');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 2');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 3');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 4');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 5');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 6');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 7');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 8');



